### PR TITLE
fix ie7 problem of attribute class vs. className

### PR DESCRIPTION
**Pull request by luobotang**

### CODE REVIEW

**Comment by luobotang** [comment]
Maybe you are right.
Maybe only a few people like me care about the **super** old browser.

**Comment by matthewmueller** [comment]
Yah, I'm -1 unless we can come up with a solution that works for both. This is a heavily depended on module, so there should be no breaking changes at this point.

**Comment by luobotang** [comment]
I have made a copy of this, 'fix' the IE7 problem then use it in my work. (I know, not a good way to do it)
The SVG support is currently not part of my work, but, I think find a solution for both is a better idea.

**Comment by matthewmueller** [comment]
Okay :-) I'm going to close this for now. If you find some time to test both, let me know and I'll reopen.

**Comment by stephenmathieson** [comment]
@luobotang no, forking is what components are all about. There's no reason you shouldn't maintain an IE7-friendly version of this component. Maybe someone else needs IE7 support but doesn't care about SVG. if I were you, I'd push a 2.0.0 tag out and start using your own version ;)

**Comment by luobotang** [comment]
@stephenmathieson Maybe you're right.
But that's a little 'complicated' & 'confused' for me .... ^_^
Thanks for your reply. Now I know that the `className` problem is not a simply bug.
@matthewmueller Thank you too, for your suggestion.

**Pull request closed without merging**
