### PR TITLE
Properly fix `component-indexof` require.

### PR DESCRIPTION
**Pull request by ockham**
Fixing `component` breakage I introduced with #27.

/cc @stephenmathieson @ronkorving

### CODE REVIEW

**Comment by ronkorving** [comment]
Appreciated :)

**Comment by AlmirKadric** [comment]
:+1:

**Comment by ockham** [comment]
Thanks for :+1:ing folks!

**Comment by ockham** [comment]
Released 1.2.6 including this fix: b2a3160
Don't have the privileges to release to npm (yet), someone else will need to do that.

**Pull request merged**
