### PR TITLE
Don't use browser alias for component-indexof dependency.

### PR DESCRIPTION
**Pull request by ockham**
This way, `component-classes` won't break node code/tests when imported.

You might want to change the release date in `History.md`

/cc @TooTallNate

### CODE REVIEW

**Comment by stephenmathieson** [comment]
lgtm short of the addition to `History.md`.. this sort of thing is handled for us via `git-release`

**Comment by ockham** [comment]
Ah sry, wasn't aware. I'll remove that.

**Comment by ockham** [comment]
Amended the commit.

**Comment by stephenmathieson** [comment]
cool, thanks dude!

**Comment by ockham** [comment]
https://www.npmjs.com/package/component-classes still shows 1.2.4 as the latest release. Manual intervention required? :-D

**Comment by stephenmathieson** [comment]
sorry, forgot to npm publish.  should be there now =)

**Comment by ockham** [comment]
@ronkorving Apologies -- filed a fix at #29.

**Pull request merged**
